# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""
NVIDIA cuSPARSELt sparse matrix multiplication operator.

This operator is NOT registered in FlagGems because:
1. The compressed format is vendor-specific and proprietary
2. There is no way to implement it portably in Triton
3. The operation requires NVIDIA's cuSPARSELt library

Users should call torch._cslt_sparse_mm() directly, which will use
the native PyTorch/CUDA implementation.

NOTE: This file exists for documentation purposes only. The operator
is not available through flag_gems.use_gems().
"""

import logging

logger = logging.getLogger(__name__)


def _cslt_sparse_mm(
    compressed_A,
    dense_B,
    bias=None,
    alpha=None,
    out_dtype=None,
    transpose_result=False,
    alg_id=0,
    split_k=1,
    split_k_mode=-1,
):
    """
    Performs sparse matrix multiplication using CUDA Sparse Linear Transformer format.

    This is a vendor-specific operation that relies on NVIDIA's cuSPARSELt library.
    The compressed_A tensor must be in cuSPARSELt compressed format (created via
    torch._cslt_compress).

    Args:
        compressed_A: Compressed sparse matrix A in cuSPARSELt format
        dense_B: Dense matrix B
        bias: Optional bias vector to add to the result
        alpha: Optional scalar multiplier
        out_dtype: Optional output data type
        transpose_result: Whether to transpose the output
        alg_id: Algorithm selection for cuSPARSELt
        split_k: Split-K parallelization factor
        split_k_mode: Split-K mode selection

    Returns:
        Result of sparse matrix multiplication

    Note:
        This function is NOT registered in FlagGems dispatch system.
        It is provided for reference only.
        Use torch._cslt_sparse_mm() directly instead.
    """
    logger.warning(
        "flag_gems._cslt_sparse_mm is not registered. "
        "Use torch._cslt_sparse_mm() directly."
    )
    raise NotImplementedError(
        "_cslt_sparse_mm cannot be implemented in portable Triton. "
        "The cuSPARSELt compressed format is vendor-specific. "
        "Use torch._cslt_sparse_mm() directly instead."
    )
